### ISSUE TITLE
fix "X or Y"

### ISSUE THREAD

**Issue by clee-dev** [clee-dev/Bucket.js#20]
![image](https://user-images.githubusercontent.com/31371384/50603935-ef9b9900-0e82-11e9-9e28-8de91f674a12.png)

**Comment by Tencona** [comment]
I attempted to replicate this problem by using just the "this or that" code as a new function called `thisorthat`, the `filterNonWords` function, `getWords` function, and `regex` constant.


The only change I made was in the `getWords` function where I changed the filter from
`.filter(x => !validUrl.isUri(x))`
to
`.filter(x => x !== 'ddddddddd')`
And to the `thisorthat` function where I made it log to the console instead of sending a message in a channel.

After doing that, I tested the code with "ddddddddd" put before the first element, between it and "or", between "or" and the second element, and after the second element in varying amounts, and I added punctuation throughout, and it always worked.

My assumption is that `validUrl.isUri(x)` is breaking.

**Comment by clee-dev** [comment]
@Tencona Could you paste the code you used?

**Comment by clee-dev** [comment]
`validUrl.isUri()` seems to be working fine for me. I think he's breaking earlier on in the `mentionedBy()` func

**Comment by clee-dev** [comment]
New example of failing message:

"@Bucket Super crunchy roll or dth roll"

**Comment by clee-dev** [comment]
"normal marshmallows or more marshmallows" also doesn't work
